<?php
class Report extends PHPJasperXML{
	public $title;
	public $heading;
	public $headerimage;
	public $watermark;
	public $address;
	public $creator ;
	public $copyright;
	public $poweredlink;
	public $reportdate;
	public $query;
	public $jrxml;
	public $filename;
	public $info_app_contact;
	public $iso_9001;
	public $iso_14001;
	public $iso_27001;
	public $rightcheck;
	public $parameter = array();
	public $password;
	public function __Construct($title="", $printSitename=false){
		global $app;
				
		$appInfo = new AppInfo();
		$appData = $appInfo->getDetails();
		$appData['info_app_bank_details'] =  nl2br($appData['info_app_bank_details']);
		$this->addData($appData);	
		$this->info_app_contact = 	$appData['info_app_contact'];	
		$this->title		=	($printSitename?($app->siteTitle.'-'):'').trim($title);
		$this->heading		=	$this->title;
		$this->headerimage	=	$app->sitePath("/img/logo.png");
		$this->watermark	=	$app->sitePath("/img/watermark.png");
		$this->rightcheck	=	$app->sitePath("/img/rightcheck.png");
		$this->address 		= 	$appData['info_app_address'];
		$this->creator 		= 	"Generated By : ".((isset($_SESSION['user_name']) && isset($_SESSION['user_type_name']))?($_SESSION['user_name']." [ ".$_SESSION['user_type_name']." ]"):"System");
		$this->copyright	=	"Copyright © ".date('Y')." safePcDisposal.co.uk";
		$this->poweredlink	=	"Powered By safePcDisposal";
		$this->reportdate	=	"Report As On : ".date("d-M Y h:i A");
		$this->filename		=	strtolower(trim($this->title)).".pdf";
		//$this->iso_9000		= 	$app->sitePath("/img/iso-9000.png");
		//$this->iso_14001	= 	$app->sitePath("/img/iso-14001.png");
		//$this->iso_27001	= 	$app->sitePath("/img/iso-27001.png");
		//$this->iso_9000_no	= 	"No. GB 18406";
		//$this->iso_14001_no	= 	"No. GB 18407";
		//$this->iso_27001_no	= 	"No. 301502018";
		$this->iso_9000_no	= 	"";
		$this->iso_14001_no	= 	"";
		$this->iso_27001_no	= 	"";
		$this->password 	=	null;
		return $this;
	}
	
	public function setFilename($name)
	{
		$this->filename		=	strtolower(trim($name)).".pdf";
		return $this;
	}
	
	public function setJRXML($xml)
	{
		global $app;
		$this->jrxml = $app->xmlPath($xml);
		return $this;
	}
	
	public function setPassword($password=null)
	{
		$this->password = $password;
	}
	
	public function addData($data=array())
	{
		$this->parameter = array_merge($this->parameter, $data);
	}
		
	public function query($sql)
	{
		$this->query = $sql;
		return $this;
	}	
	
	public function generate()
	{
		$phpjasperxml = new PHPJasperXML();	
		$xml =  simplexml_load_file($this->jrxml);
		$phpjasperxml->outputfilename = $this->filename;
		$phpjasperxml->arrayParameter = array_merge($this->parameter, get_object_vars($this));
		//var_dump($phpjasperxml->arrayParameter);die;
		$phpjasperxml->protection = $this->password;
		$phpjasperxml->xml_dismantle($xml);
		$phpjasperxml->transferDBtoArray(DB_HOST,DB_USER,DB_PASSWORD,DB_NAME, 'mysqli');		
		$phpjasperxml->outpage("I", $this->filename);
	}
}
?>